name: Test and Release
on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
  pull_request:

jobs:
  all-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/workflows/install

      - name: Install e2e dependencies
        run: |
          cd e2e/site
          pnpm install

      - name: Copy new dist
        run: |
          rm -rf e2e/site/node_modules/elter/dist
          cp -r dist e2e/site/node_modules/elter/

      - name: Run Jest tests
        run: |
          pnpm exec jest --ci --coverage --reporters=github-actions --reporters=summary

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage

      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps

      - name: Start Next.js Dev Server
        run: pnpm run dev:e2e &
        env:
          CI: true

      - name: Run Playwright tests
        run: pnpm exec playwright test

      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report

  release:
    runs-on: ubuntu-latest
    needs: ['all-tests']
    if: startsWith(github.ref, 'refs/tags/v')
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/workflows/install

      - name: Publish package
        run: |
          mkdir publish
          cp -r bin compiler dist next license readme.md npm/package.json ./publish
          cd publish
          npm publish --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
